services:
  - type: web
    name: st-berchmans-aids
    runtime: node
    plan: free
    region: singapore
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
