import { Student, Project } from './types';

export const DEFAULT_STUDENTS: Student[] = [
  {
    id: 'stu-1',
    name: 'Rahul V. Nair',
    rollNo: '401',
    batch: 'B.Sc. AI & DS (2026 - 2030)',
    bloodGroup: 'O+ve',
    email: 'rahul.nair@student.sbcollege.ac.in',
    phone: '+91 98470 12345',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    linkedIn: 'https://linkedin.com/in/rahul-v-nair',
    portfolioUrl: 'https://github.com/rahulvnair',
    skills: ['PyTorch', 'Computer Vision', 'Next.js', 'Python', 'OpenCV'],
    wings: ['tech_team', 'nss'],
    bio: 'AI & Data Science enthusiast passionate about Malayalam Natural Language Processing and autonomous computer vision for precision agriculture.',
    approvalStatus: 'approved',
  },
  {
    id: 'stu-2',
    name: 'Ananya S. Kumar',
    rollNo: '402',
    batch: 'B.Sc. AI & DS (2026 - 2030)',
    bloodGroup: 'A+ve',
    email: 'ananya.kumar@student.sbcollege.ac.in',
    phone: '+91 94471 23456',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
    linkedIn: 'https://linkedin.com/in/ananya-s-kumar',
    portfolioUrl: 'https://ananya-ai.dev',
    skills: ['Data Analytics', 'Power BI', 'Scikit-Learn', 'SQL', 'FastAPI'],
    wings: ['media_team', 'sports'],
    bio: 'Data Analyst focusing on financial predictive modeling and interactive dashboard visualisations for enterprise decision support.',
    approvalStatus: 'approved',
  },
  {
    id: 'stu-3',
    name: 'Kevin P. Thomas',
    rollNo: '403',
    batch: 'B.Sc. AI & DS (2026 - 2030)',
    bloodGroup: 'B+ve',
    email: 'kevin.thomas@student.sbcollege.ac.in',
    phone: '+91 97452 34567',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    linkedIn: 'https://linkedin.com/in/kevin-p-thomas',
    portfolioUrl: 'https://github.com/kevinpthomas',
    skills: ['TensorFlow', 'IoT', 'Raspberry Pi', 'Embedded AI', 'C++'],
    wings: ['tech_team', 'ncc'],
    bio: 'Embedded Systems & AI Engineer building smart campus attendance hardware and edge AI surveillance models.',
    approvalStatus: 'approved',
  },
  {
    id: 'stu-4',
    name: 'Devika R. Menon',
    rollNo: '404',
    batch: 'B.Sc. AI & DS (2026 - 2030)',
    bloodGroup: 'AB+ve',
    email: 'devika.menon@student.sbcollege.ac.in',
    phone: '+91 96333 45678',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    linkedIn: 'https://linkedin.com/in/devika-r-menon',
    portfolioUrl: 'https://devikamenon.tech',
    skills: ['NLP', 'LLMs', 'RAG Pipelines', 'LangChain', 'Python'],
    wings: ['media_team', 'nss'],
    bio: 'Conversational AI researcher crafting domain-specific retrieval augmented generation (RAG) chatbots for academic knowledge systems.',
    approvalStatus: 'approved',
  },
  {
    id: 'stu-5',
    name: 'Arun K. George',
    rollNo: '405',
    batch: 'B.Sc. AI & DS (2026 - 2030)',
    bloodGroup: 'O-ve',
    email: 'arun.george@student.sbcollege.ac.in',
    phone: '+91 98954 56789',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    linkedIn: 'https://linkedin.com/in/arun-k-george',
    portfolioUrl: 'https://github.com/arungeorge-ai',
    skills: ['Deep Learning', 'PyTorch', 'Django', 'Docker', 'PostgreSQL'],
    wings: ['tech_team', 'sports'],
    bio: 'Full-stack AI developer with a focus on scalable cloud backend architectures and automated model deployment pipelines.',
    approvalStatus: 'approved',
  },
  {
    id: 'stu-6',
    name: 'Sneha Elizabeth',
    rollNo: '406',
    batch: 'B.Sc. AI & DS (2026 - 2030)',
    bloodGroup: 'A-ve',
    email: 'sneha.elizabeth@student.sbcollege.ac.in',
    phone: '+91 94965 67890',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    linkedIn: 'https://linkedin.com/in/sneha-elizabeth',
    portfolioUrl: 'https://snehaelizabeth.dev',
    skills: ['Machine Learning', 'Data Mining', 'React.js', 'Pandas', 'Matplotlib'],
    wings: ['nss', 'media_team'],
    bio: 'Data Visualization and Machine Learning specialist interested in health-tech analytics and community welfare data science.',
    approvalStatus: 'approved',
  }
];

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'Malayalam Agri-Vision AI',
    description: 'Autonomous computer vision pipeline and Mobile App identifying crop diseases in pepper, rubber, and cardamom crops across Kerala farms using custom-trained YOLOv8 models.',
    category: 'Computer Vision',
    status: 'completed',
    teamMembers: ['Rahul V. Nair', 'Kevin P. Thomas', 'Arun K. George'],
    techStack: ['PyTorch', 'YOLOv8', 'OpenCV', 'React Native', 'FastAPI'],
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&h=500&fit=crop',
    githubUrl: 'https://github.com/sb-aids/agri-vision-malayalam',
    demoUrl: 'https://agri-vision.sbcollege.ac.in',
    documentationUrl: 'https://github.com/sb-aids/agri-vision-malayalam/wiki',
    rating: 4.9,
    ratingCount: 14,
    comments: [
      {
        id: 'c-1',
        projectId: 'proj-1',
        userName: 'Chief Administrator',
        userRole: 'admin',
        rating: 5,
        comment: 'Outstanding practical application of computer vision for local agricultural challenges in Kottayam district.',
        createdAt: '2026-08-15',
        approved: true,
      },
      {
        id: 'c-2',
        projectId: 'proj-1',
        userName: 'Devika R. Menon',
        userRole: 'student',
        rating: 5,
        comment: 'The inference speed on mobile devices is exceptionally impressive!',
        createdAt: '2026-08-18',
        approved: true,
      }
    ],
    submittedBy: 'Rahul V. Nair',
    submittedAt: 'August 10, 2026',
    isApproved: true,
  },
  {
    id: 'proj-2',
    title: 'Smart Campus Edge Attendance & CCTV Analytics',
    description: 'Embedded camera system using Raspberry Pi 4 and edge tensor accelerators to automatically record autonomous classroom attendance with anti-spoofing liveness detection.',
    category: 'IoT & Edge AI',
    status: 'completed',
    teamMembers: ['Kevin P. Thomas', 'Ananya S. Kumar'],
    techStack: ['TensorFlow Lite', 'Raspberry Pi', 'OpenCV', 'Next.js', 'PostgreSQL'],
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=500&fit=crop',
    githubUrl: 'https://github.com/sb-aids/smart-attendance-edge',
    demoUrl: 'https://attendance.sbcollege.ac.in',
    rating: 4.8,
    ratingCount: 9,
    comments: [
      {
        id: 'c-3',
        projectId: 'proj-2',
        userName: 'Chief Administrator',
        userRole: 'admin',
        rating: 5,
        comment: 'Successfully piloted in Centenary Lab with over 99.4% accuracy.',
        createdAt: '2026-08-22',
        approved: true,
      }
    ],
    submittedBy: 'Kevin P. Thomas',
    submittedAt: 'August 20, 2026',
    isApproved: true,
  },
  {
    id: 'proj-3',
    title: 'Malayalam Academic Assistant RAG System',
    description: 'Domain-adapted retrieval-augmented generation model powered by fine-tuned Llama-3, providing instant multilingual query answers for autonomous college syllabus and regulations.',
    category: 'Natural Language Processing',
    status: 'upcoming',
    teamMembers: ['Devika R. Menon', 'Rahul V. Nair'],
    techStack: ['Python', 'LangChain', 'FAISS', 'Ollama', 'Next.js'],
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=500&fit=crop',
    githubUrl: 'https://github.com/sb-aids/malayalam-academic-rag',
    demoUrl: '',
    rating: 5.0,
    ratingCount: 5,
    comments: [],
    submittedBy: 'Devika R. Menon',
    submittedAt: 'September 01, 2026',
    isApproved: true,
  },
  {
    id: 'proj-4',
    title: 'Financial Risk & Stock Predictive Analytics Dashboard',
    description: 'Time-series forecasting model analyzing NSE stock indices and macroeconomic datasets, generating interactive risk assessment heatmaps built during EY Skill Hub program.',
    category: 'Data Science & Finance',
    status: 'completed',
    teamMembers: ['Ananya S. Kumar', 'Sneha Elizabeth'],
    techStack: ['Power BI', 'Python', 'XGBoost', 'Prophet', 'Pandas'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop',
    githubUrl: 'https://github.com/sb-aids/financial-analytics-ey',
    demoUrl: 'https://ey-analytics.sbcollege.ac.in',
    rating: 4.7,
    ratingCount: 11,
    comments: [],
    submittedBy: 'Ananya S. Kumar',
    submittedAt: 'August 28, 2026',
    isApproved: true,
  }
];
