import { 
  Faculty, 
  Student, 
  Project, 
  EventItem, 
  Achievement, 
  NoteItem, 
  SyllabusItem, 
  Announcement, 
  SkillHubCourse 
} from './types';

export const COLLEGE_INFO = {
  name: "St. Berchmans College (Autonomous)",
  nameMl: "സെന്റ് ബെർക്ക്മാൻസ് കോളേജ് (ഓട്ടോണമസ്)",
  departmentName: "Department of Artificial Intelligence & Data Science",
  departmentNameMl: "ആർട്ടിഫിഷ്യൽ ഇന്റലിജൻസ് & ഡാറ്റ സയൻസ് വകുപ്പ്",
  location: "Changanassery, Kottayam District, Kerala - 686101",
  established: 1922,
  founder: "Venerable Mar Thomas Kurialacherry (Bishop of Changanassery)",
  management: "Archdiocesan Educational and Charitable Trust of Changanacherry",
  accreditation: "NAAC Re-accredited with A+ Grade | NIRF Top 100 Indian Colleges",
  autonomyYear: 2014,
  patronSaint: "St. John Berchmans (1599 - 1621)",
  motto: "Maximi facere minima",
  mottoTranslation: "Do the most with the least / Perfection in ordinary duties",
  email: "aids@sbcollege.ac.in",
  phone: "+91 481 2420025",
  website: "https://sbcollege.ac.in",
  images: {
    hero: "/images/sb college centre full.jpg",
    aboutCampus: "/images/sb college left full.jpg",
    logo: "/images/sb college logo.jpg",
    missionVision: "/images/Mission and vission.png",
  }
};

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Applications Open for B.Voc & M.Sc AI & Data Science 2026-27 Batch",
    titleMl: "2026-27 ബാച്ചിലേക്കുള്ള ബി.വോക് & എം.എസ്.സി എ.ഐ പ്രവേശനത്തിന് അപേക്ഷ ക്ഷണിച്ചു",
    date: "September 05, 2026",
    category: "academic",
    content: "Online registration for undergraduate and postgraduate admissions in the Department of AI and Data Science is now live on the college admission portal.",
    link: "/portal",
    isUrgent: true,
  },
  {
    id: "ann-2",
    title: "SB AI Datathon 2026 Announced — Cash Prize Pool of ₹50,000",
    titleMl: "എസ്.ബി എ.ഐ ഡാറ്റാത്തോൺ 2026 പ്രഖ്യാപിച്ചു — ₹50,000 സമ്മാനത്തുക",
    date: "August 28, 2026",
    category: "event",
    content: "Annual 36-hour hackathon hosted by the Tech Team focusing on Malayalam NLP and Computer Vision for precision farming.",
    link: "/events",
    isUrgent: false,
  },
  {
    id: "ann-3",
    title: "Semester IV & VI Autonomous End-Semester Examination Schedule Published",
    titleMl: "സെമസ്റ്റർ 4, 6 ഓട്ടോണമസ് പരീക്ഷാ ടൈംടേബിൾ പ്രസിദ്ധീകരിച്ചു",
    date: "August 20, 2026",
    category: "exam",
    content: "Theory and practical examination schedules for academic year 2025-26 have been uploaded under the Downloads & Syllabus section.",
    link: "/academics/downloads",
    isUrgent: false,
  }
];

export const FACULTY_MEMBERS: Faculty[] = [
  {
    id: "fac-1",
    name: "Dr. Joseph Varghese",
    designation: "Head of the Department & Associate Professor",
    qualification: "Ph.D. in Computer Science & Engineering (IIT Madras), M.Tech (NIT Calicut)",
    specialization: "Deep Learning, Large Language Models, Neural Architecture Search",
    experience: "16+ Years Academic & Research Experience",
    email: "hod.aids@sbcollege.ac.in",
    phone: "+91 94471 23456",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face",
    researchInterests: ["Generative AI", "Low-Resource Indic NLP", "Medical Image Segmentation"],
    portfolioUrl: "https://scholar.google.com",
    order: 1,
  },
  {
    id: "fac-2",
    name: "Prof. Priya Mathew",
    designation: "Assistant Professor & Student Activities Coordinator",
    qualification: "M.Tech in Data Analytics (CUSAT), B.Tech (MG University), NET-JRF",
    specialization: "Big Data Systems, Distributed Computing, Predictive Modeling",
    experience: "10+ Years Teaching & Industry Consulting",
    email: "priya.mathew@sbcollege.ac.in",
    phone: "+91 94472 34567",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face",
    researchInterests: ["Distributed Big Data", "Graph Neural Networks", "Time-Series Forecasting"],
    portfolioUrl: "https://linkedin.com",
    order: 2,
  },
  {
    id: "fac-3",
    name: "Dr. Arun Kumar R.",
    designation: "Assistant Professor & Tech Team Mentor",
    qualification: "Ph.D. in Artificial Intelligence (Amrita Vishwa Vidyapeetham), M.E.",
    specialization: "Computer Vision, Autonomous Systems, Edge AI, IoT",
    experience: "8+ Years Research & Teaching",
    email: "arun.kumar@sbcollege.ac.in",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    researchInterests: ["Object Detection in Drone Imagery", "Edge Computing for Agriculture", "Robotics"],
    portfolioUrl: "https://github.com",
    order: 3,
  },
  {
    id: "fac-4",
    name: "Prof. Anju Thomas",
    designation: "Assistant Professor & Skill Hub Liaison",
    qualification: "M.Sc Computer Science, M.Phil, UGC-NET",
    specialization: "Statistical Machine Learning, Data Visualization, Python for DS",
    experience: "9+ Years Teaching Experience",
    email: "anju.thomas@sbcollege.ac.in",
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
    researchInterests: ["Educational Data Mining", "Bioinformatics", "Sentiment Analysis"],
    portfolioUrl: "https://linkedin.com",
    order: 4,
  }
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: "stu-101",
    name: "Kevin Paul",
    rollNo: "220101",
    batch: "B.Voc AI & DS (2022 - 2025)",
    bloodGroup: "O+ve",
    email: "kevin.paul@student.sbcollege.ac.in",
    photo: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop&crop=face",
    linkedIn: "https://linkedin.com/in/kevin-paul-ai",
    portfolioUrl: "https://kevinpaul.dev",
    skills: ["Python", "PyTorch", "Next.js", "Computer Vision", "Docker"],
    wings: ["tech_team", "sports"],
    bio: "Passionate about autonomous edge systems and full-stack AI development. Lead developer on the Campus Autonomous Rover project.",
    approvalStatus: "approved",
  },
  {
    id: "stu-102",
    name: "Ananya Roy",
    rollNo: "220102",
    batch: "B.Voc AI & DS (2022 - 2025)",
    bloodGroup: "A+ve",
    email: "ananya.roy@student.sbcollege.ac.in",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    linkedIn: "https://linkedin.com/in/ananya-roy-ds",
    portfolioUrl: "https://ananyaroy.github.io",
    skills: ["Malayalam NLP", "Transformers", "FastAPI", "React", "PostgreSQL"],
    wings: ["tech_team", "media_team"],
    bio: "NLP researcher and open-source enthusiast. Building low-resource speech-to-text models for Malayalam agricultural advisories.",
    approvalStatus: "approved",
  },
  {
    id: "stu-103",
    name: "Rahul Krishna",
    rollNo: "230105",
    batch: "M.Sc AI (2023 - 2025)",
    bloodGroup: "B+ve",
    email: "rahul.k@student.sbcollege.ac.in",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    linkedIn: "https://linkedin.com/in/rahulkrishna",
    portfolioUrl: "https://rahulk.tech",
    skills: ["Deep Learning", "TensorFlow", "Video Editing", "Three.js", "Blender"],
    wings: ["media_team"],
    bio: "Visual computing specialist and lead media producer for the department's technical podcasts and creative reels.",
    approvalStatus: "approved",
  },
  {
    id: "stu-104",
    name: "Sandra Joseph",
    rollNo: "230112",
    batch: "B.Voc AI & DS (2023 - 2026)",
    bloodGroup: "AB+ve",
    email: "sandra.j@student.sbcollege.ac.in",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    linkedIn: "https://linkedin.com/in/sandra-joseph",
    portfolioUrl: "https://sandraj.me",
    skills: ["Data Analysis", "Pandas", "Scikit-Learn", "Community Engagement", "UI/UX"],
    wings: ["nss"],
    bio: "NSS volunteer leader committed to applying data science for rural health surveys and local community development programs.",
    approvalStatus: "approved",
  },
  {
    id: "stu-105",
    name: "Alan George",
    rollNo: "230118",
    batch: "B.Voc AI & DS (2023 - 2026)",
    bloodGroup: "O-ve",
    email: "alan.george@student.sbcollege.ac.in",
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
    linkedIn: "https://linkedin.com/in/alangeorge",
    skills: ["Cybersecurity", "Python", "Linux Administration", "Drill & Command"],
    wings: ["ncc"],
    bio: "NCC Cadet Senior Under Officer balancing military discipline with machine learning security and anomaly detection.",
    approvalStatus: "approved",
  },
  {
    id: "stu-106",
    name: "Tony Sebastian",
    rollNo: "240104",
    batch: "B.Voc AI & DS (2024 - 2027)",
    bloodGroup: "A-ve",
    email: "tony.s@student.sbcollege.ac.in",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
    skills: ["Computer Vision", "Pose Estimation", "Basketball", "React Native"],
    wings: ["sports"],
    bio: "College Basketball Team captain researching AI-driven athletic pose estimation and sports biomechanics analytics.",
    approvalStatus: "approved",
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-1",
    title: "AgriMalayalam: Speech-Driven Disease Diagnosis for Farmers",
    description: "An offline-first mobile and web application utilizing fine-tuned Whisper for Malayalam dialect speech recognition and Vision Transformer (ViT) to diagnose crop leaf infections in Kuttanad paddy fields.",
    category: "Agriculture AI / NLP",
    status: "completed",
    teamMembers: ["Ananya Roy", "Kevin Paul"],
    techStack: ["PyTorch", "Whisper", "ViT", "FastAPI", "React Native"],
    image: "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=800&h=500&fit=crop",
    demoUrl: "https://agri-malayalam.demo.sbcollege.ac.in",
    githubUrl: "https://github.com/sbcollege-aids/agri-malayalam",
    documentationUrl: "#",
    rating: 4.9,
    ratingCount: 14,
    submittedBy: "Ananya Roy",
    submittedAt: "July 2026",
    isApproved: true,
    comments: [
      {
        id: "c-1",
        projectId: "proj-1",
        userName: "Dr. Joseph Varghese",
        userRole: "faculty",
        rating: 5,
        comment: "Excellent use of Whisper fine-tuning for regional dialect accents. Highly practical for our local agrarian communities.",
        createdAt: "July 24, 2026",
        approved: true,
      },
      {
        id: "c-2",
        projectId: "proj-1",
        userName: "Alan George",
        userRole: "student",
        rating: 5,
        comment: "Tested this in our village panchayat. The response speed even on 3G is remarkably quick!",
        createdAt: "August 02, 2026",
        approved: true,
      }
    ]
  },
  {
    id: "proj-2",
    title: "CampusRover: Autonomous Navigation & Surveillance Bot",
    description: "A compact wheeled mobile robot outfitted with LiDAR, stereo cameras, and an NVIDIA Jetson Orin Nano, executing SLAM and visual obstacle avoidance across the St. Berchmans campus corridors.",
    category: "Robotics & Edge AI",
    status: "completed",
    teamMembers: ["Kevin Paul", "Tony Sebastian"],
    techStack: ["ROS 2", "YOLOv8", "Jetson Orin", "LiDAR", "Python"],
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=500&fit=crop",
    demoUrl: "https://youtube.com/watch?v=sample",
    githubUrl: "https://github.com/sbcollege-aids/campus-rover",
    rating: 4.8,
    ratingCount: 19,
    submittedBy: "Kevin Paul",
    submittedAt: "June 2026",
    isApproved: true,
    comments: [
      {
        id: "c-3",
        projectId: "proj-2",
        userName: "Dr. Arun Kumar R.",
        userRole: "faculty",
        rating: 5,
        comment: "Impressive path planning inside the centenary library. Ready for presentation at the National Robotics Symposium.",
        createdAt: "June 15, 2026",
        approved: true,
      }
    ]
  },
  {
    id: "proj-3",
    title: "BerchmansSmartLens: Real-Time Classroom Attention & Analytics",
    description: "Privacy-preserving edge computer vision framework that evaluates overall lecture engagement metrics without recording or storing identifiable student facial biometrics.",
    category: "Computer Vision / EdTech",
    status: "upcoming",
    teamMembers: ["Rahul Krishna", "Sandra Joseph"],
    techStack: ["MediaPipe", "TensorRT", "Edge TPU", "Next.js"],
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&h=500&fit=crop",
    rating: 4.6,
    ratingCount: 7,
    submittedBy: "Rahul Krishna",
    submittedAt: "August 2026",
    isApproved: true,
    comments: []
  },
  {
    id: "proj-4",
    title: "MedVoice: Clinical Documentation Assistant in Malayalam & English",
    description: "Automated electronic health record synthesis tool that transcribes bilingual clinical consultations between doctors and rural patients into structured HL7 FHIR records.",
    category: "Healthcare AI / LLMs",
    status: "upcoming",
    teamMembers: ["Ananya Roy", "Kevin Paul", "Sandra Joseph"],
    techStack: ["Llama-3-70B", "LoRA", "FastAPI", "PostgreSQL", "Tailwind"],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=500&fit=crop",
    rating: 5.0,
    ratingCount: 8,
    submittedBy: "Ananya Roy",
    submittedAt: "September 2026",
    isApproved: true,
    comments: []
  }
];

export const EVENTS: EventItem[] = [
  {
    id: "evt-1",
    title: "Kerala State Autonomous AI Summit & Hackathon 2026",
    description: "A flagship 2-day technical symposium bringing together 400+ researchers, student builders, and AI leaders to discuss foundational models, ethical data frameworks, and industrial deployment.",
    date: "October 14-15, 2026",
    time: "09:00 AM - 05:30 PM",
    venue: "Kavukattu Hall, St. Berchmans College",
    organizer: "Department of AI & DS & Tech Team",
    registrationUrl: "https://sbcollege.ac.in/events/ai-summit-2026",
    posterImage: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop",
    guestSpeaker: "Dr. Gopika Nair (Principal Scientist, Google DeepMind India)",
    status: "upcoming",
  },
  {
    id: "evt-2",
    title: "Hands-on Workshop: Building Production AI Agents with PyTorch & LLMs",
    description: "Intensive 3-day bootcamp exploring LangGraph, vector databases, and multi-agent coordination for enterprise automation.",
    date: "September 26-28, 2026",
    time: "02:45 PM - 05:00 PM (SB Skill Hub)",
    venue: "Centenary AI Research Lab",
    organizer: "SB Skill Hub in collaboration with ICTAK",
    registrationUrl: "https://sbcollege.ac.in/skill-hub/register",
    posterImage: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&h=500&fit=crop",
    guestSpeaker: "Mr. Thomas Cherian (AI Lead, EY GDS)",
    status: "upcoming",
  },
  {
    id: "evt-3",
    title: "SB National Datathon 2025: Predictive Climate Modeling for Western Ghats",
    description: "36-hour non-stop datathon solving flash-flood and landslide predictions using historical satellite radar telemetry.",
    date: "December 08-09, 2025",
    time: "Completed",
    venue: "Main Auditorium",
    organizer: "Department of AI & DS",
    posterImage: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&h=500&fit=crop",
    status: "completed",
  }
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "ach-1",
    title: "1st Place Champions — National AgriTech AI Hackathon 2026",
    description: "Students of B.Voc AI & Data Science bagged first place and a ₹1,00,000 cash grant for their project 'AgriMalayalam', recognized by the Ministry of Agriculture.",
    date: "August 2026",
    category: "National Award",
    image: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&h=500&fit=crop",
    taggedStudentIds: ["stu-102", "stu-101"],
    studentNames: ["Ananya Roy", "Kevin Paul"],
  },
  {
    id: "ach-2",
    title: "Finalist at Smart India Hackathon (SIH 2025)",
    description: "Team 'Berchmans Neural Net' selected among top 5 finalists nationwide for edge computer vision surveillance system.",
    date: "November 2025",
    category: "National Competition",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=500&fit=crop",
    taggedStudentIds: ["stu-101", "stu-103"],
    studentNames: ["Kevin Paul", "Rahul Krishna"],
  },
  {
    id: "ach-3",
    title: "Best Research Paper Award at IEEE International Conference (ICACCI)",
    description: "Joint faculty-student paper titled 'Efficient Transformer Attention for Dialectal Speech Processing' awarded Best Technical Paper.",
    date: "January 2026",
    category: "Research Excellence",
    image: "https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=800&h=500&fit=crop",
    taggedStudentIds: ["stu-102"],
    studentNames: ["Ananya Roy"],
  }
];

export const LECTURE_NOTES: NoteItem[] = [
  {
    id: "note-1",
    title: "Module 1-4: Mathematical Foundations of Data Science & Linear Algebra",
    subject: "Mathematics for Data Science (AID2101)",
    semester: 1,
    academicYear: "2025-26",
    description: "Comprehensive notes covering vector spaces, eigenvalues, singular value decomposition (SVD), and matrix calculus for gradient descent.",
    fileUrl: "/downloads/notes/Math_Foundations_Data_Science.pdf",
    fileSize: "4.2 MB",
    uploadedBy: "Dr. Joseph Varghese",
    uploadedAt: "August 12, 2026",
    downloadCount: 342,
  },
  {
    id: "note-2",
    title: "Complete Lecture Guide: Deep Neural Architectures & Backpropagation",
    subject: "Deep Learning Foundations (AID3201)",
    semester: 3,
    academicYear: "2025-26",
    description: "Multi-layer perceptrons, computational graphs, regularization, Adam optimizers, and implementation from scratch in PyTorch.",
    fileUrl: "/downloads/notes/Deep_Learning_Lecture_Notes.pdf",
    fileSize: "8.7 MB",
    uploadedBy: "Dr. Arun Kumar R.",
    uploadedAt: "August 20, 2026",
    downloadCount: 521,
  },
  {
    id: "note-3",
    title: "Distributed Big Data Systems & Apache Spark Architecture",
    subject: "Big Data Analytics & Cloud (AID4202)",
    semester: 4,
    academicYear: "2025-26",
    description: "HDFS, RDDs, DataFrames, Spark Streaming, and real-time Kafka integration guide with hands-on lab exercises.",
    fileUrl: "/downloads/notes/Big_Data_Analytics_Notes.pdf",
    fileSize: "6.1 MB",
    uploadedBy: "Prof. Priya Mathew",
    uploadedAt: "September 02, 2026",
    downloadCount: 289,
  },
  {
    id: "note-4",
    title: "Natural Language Processing: From Word2Vec to Modern Attention Transformers",
    subject: "Natural Language Processing (AID5103)",
    semester: 5,
    academicYear: "2025-26",
    description: "Tokenization, RNNs/LSTMs, encoder-decoder architectures, scaled dot-product self-attention, and Hugging Face pipelines.",
    fileUrl: "/downloads/notes/NLP_Transformers_Notes.pdf",
    fileSize: "9.4 MB",
    uploadedBy: "Prof. Anju Thomas",
    uploadedAt: "September 04, 2026",
    downloadCount: 415,
  }
];

export const SYLLABUS_LIST: SyllabusItem[] = [
  {
    id: "syl-1",
    title: "B.Voc Artificial Intelligence & Data Science Curriculum (Regulations 2024)",
    programme: "B.Voc AI & Data Science",
    academicYear: "2024 - 2027",
    semester: 1,
    fileUrl: "/downloads/syllabus/BVoc_AIDS_Syllabus_2024_2027.pdf",
    fileSize: "2.8 MB",
  },
  {
    id: "syl-2",
    title: "M.Sc Artificial Intelligence Post-Graduate Syllabus (Autonomous Framework)",
    programme: "M.Sc AI",
    academicYear: "2024 - 2026",
    fileUrl: "/downloads/syllabus/MSc_AI_Syllabus_2024_2026.pdf",
    fileSize: "3.1 MB",
  },
  {
    id: "syl-3",
    title: "B.Voc Artificial Intelligence & Data Science (Regulations 2022 Archive)",
    programme: "B.Voc AI & Data Science",
    academicYear: "2022 - 2025",
    fileUrl: "/downloads/syllabus/BVoc_AIDS_Syllabus_2022_2025.pdf",
    fileSize: "2.4 MB",
  }
];

export const SKILL_HUB_COURSES: SkillHubCourse[] = [
  {
    id: "sk-1",
    title: "Generative AI & Enterprise LLM Engineering",
    partner: "EY GDS & ICT Academy of Kerala (ICTAK)",
    durationHours: 45,
    mode: "Hybrid (Centenary Lab + Online)",
    category: "Artificial Intelligence",
    description: "Hands-on instruction in fine-tuning, RAG pipelines, prompt engineering, and deploying cost-effective LLMs."
  },
  {
    id: "sk-2",
    title: "Full-Stack AI Application Development",
    partner: "Additional Skill Acquisition Programme (ASAP Kerala)",
    durationHours: 45,
    mode: "Campus Lab",
    category: "Software Development",
    description: "Building production web apps connecting Next.js, FastAPI, PostgreSQL, and deployed machine learning APIs."
  },
  {
    id: "sk-3",
    title: "Advanced Data Analytics & Financial Intelligence",
    partner: "Ernst & Young (EY)",
    durationHours: 45,
    mode: "Hybrid",
    category: "Data Science",
    description: "Predictive financial modeling, Power BI enterprise dashboards, and time-series risk prediction algorithms."
  },
  {
    id: "sk-4",
    title: "Digital Media Production & Visual Effects for AI",
    partner: "Centre for Development of Imaging Technology (CDIT)",
    durationHours: 45,
    mode: "Multimedia Lab",
    category: "Media & Imaging",
    description: "Digital imaging workflows, generative video editing, 3D visualization, and synthetic dataset creation."
  },
  {
    id: "sk-5",
    title: "Professional Corporate English & International Communication",
    partner: "Burlington English",
    durationHours: 45,
    mode: "Language Lab (Interactive)",
    category: "Communication",
    description: "Business communication, technical presentation polish, and global corporate interview readiness."
  },
  {
    id: "sk-6",
    title: "Defence Technology & Strategic Aptitude",
    partner: "Berchmans Defence Academy (BEDA)",
    durationHours: 45,
    mode: "Campus Classroom",
    category: "Defence & Leadership",
    description: "Preparation for defence technical entries, physical fitness leadership, and strategic data technologies."
  }
];

export const WINGS_INFO = [
  {
    id: "nss",
    name: "National Service Scheme (NSS)",
    tagline: "Not Me But You — Social Impact through Technology",
    description: "Empowering rural communities around Changanassery through digital literacy camps, blood donation drives, and environmental sustainability initiatives.",
    color: "#2E7D50",
    iconName: "HeartHandshake",
  },
  {
    id: "ncc",
    name: "National Cadet Corps (NCC)",
    tagline: "Unity and Discipline",
    description: "Army and Naval wings instilling leadership, character, resilience, and readiness to serve the nation.",
    color: "#12192B",
    iconName: "Shield",
  },
  {
    id: "sports",
    name: "Department Sports Wing",
    tagline: "Excellence, Teamwork & Athletic Vigour",
    description: "Representing St. Berchmans in inter-collegiate football, basketball, cricket, and athletic tournaments.",
    color: "#FA7538",
    iconName: "Trophy",
  },
  {
    id: "tech_team",
    name: "Tech Team",
    tagline: "Building Open Source & Campus Innovation",
    description: "The technical spearhead of the department managing web infrastructure, hosting hackathons, and developing automation tools for college administration.",
    color: "#FA7538",
    iconName: "Code",
  },
  {
    id: "media_team",
    name: "Media Wing",
    tagline: "Creative Storytelling, Podcasting & Design",
    description: "Curating the department's visual identity, event photography, tech recap videos, newsletters, and social media outreach.",
    color: "#12192B",
    iconName: "Video",
  },
];
